baseURL = 'http://furmanczak.de/'
languageCode = 'de-de'
title = 'furmanczak.de'
theme = 'blogTheme'
summaryLength = '18'
email = "nikolai.furmanczak@gmx.de"
copyright = 'Â© 2024 furmanczak.de'
tableOfContents = true

[markup]
  [markup.tableOfContents]
    startLevel = 1
    ordered = true
    endLevel = 6
[markup.goldmark]
[markup.goldmark.renderer]
hardWraps = true
unsafe = true

[taxonomies]
tag = 'tags'

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3
[[menu.main]]
name = "About"
url = "/about/"
weight = 4
